// Code generated by qtc from "query_range_response.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line app/vmselect/loki/query_range_response.qtpl:1
package loki

//line app/vmselect/loki/query_range_response.qtpl:1
import (
	"github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/netstorage"
)

// QueryRangeResponse generates response for /api/v1/query_range.See https://prometheus.io/docs/prometheus/latest/querying/api/#range-queries

//line app/vmselect/loki/query_range_response.qtpl:8
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line app/vmselect/loki/query_range_response.qtpl:8
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line app/vmselect/loki/query_range_response.qtpl:8
func StreamQueryRangeResponse(qw422016 *qt422016.Writer, rs []netstorage.Result) {
//line app/vmselect/loki/query_range_response.qtpl:8
	qw422016.N().S(`{"status":"success","data":{"resultType":"matrix","result":[`)
//line app/vmselect/loki/query_range_response.qtpl:14
	if len(rs) > 0 {
//line app/vmselect/loki/query_range_response.qtpl:15
		streamqueryRangeLine(qw422016, &rs[0])
//line app/vmselect/loki/query_range_response.qtpl:16
		rs = rs[1:]

//line app/vmselect/loki/query_range_response.qtpl:17
		for i := range rs {
//line app/vmselect/loki/query_range_response.qtpl:17
			qw422016.N().S(`,`)
//line app/vmselect/loki/query_range_response.qtpl:18
			streamqueryRangeLine(qw422016, &rs[i])
//line app/vmselect/loki/query_range_response.qtpl:19
		}
//line app/vmselect/loki/query_range_response.qtpl:20
	}
//line app/vmselect/loki/query_range_response.qtpl:20
	qw422016.N().S(`]}}`)
//line app/vmselect/loki/query_range_response.qtpl:24
}

//line app/vmselect/loki/query_range_response.qtpl:24
func WriteQueryRangeResponse(qq422016 qtio422016.Writer, rs []netstorage.Result) {
//line app/vmselect/loki/query_range_response.qtpl:24
	qw422016 := qt422016.AcquireWriter(qq422016)
//line app/vmselect/loki/query_range_response.qtpl:24
	StreamQueryRangeResponse(qw422016, rs)
//line app/vmselect/loki/query_range_response.qtpl:24
	qt422016.ReleaseWriter(qw422016)
//line app/vmselect/loki/query_range_response.qtpl:24
}

//line app/vmselect/loki/query_range_response.qtpl:24
func QueryRangeResponse(rs []netstorage.Result) string {
//line app/vmselect/loki/query_range_response.qtpl:24
	qb422016 := qt422016.AcquireByteBuffer()
//line app/vmselect/loki/query_range_response.qtpl:24
	WriteQueryRangeResponse(qb422016, rs)
//line app/vmselect/loki/query_range_response.qtpl:24
	qs422016 := string(qb422016.B)
//line app/vmselect/loki/query_range_response.qtpl:24
	qt422016.ReleaseByteBuffer(qb422016)
//line app/vmselect/loki/query_range_response.qtpl:24
	return qs422016
//line app/vmselect/loki/query_range_response.qtpl:24
}

//line app/vmselect/loki/query_range_response.qtpl:26
func streamqueryRangeLine(qw422016 *qt422016.Writer, r *netstorage.Result) {
//line app/vmselect/loki/query_range_response.qtpl:26
	qw422016.N().S(`{"metric":`)
//line app/vmselect/loki/query_range_response.qtpl:28
	streammetricNameObject(qw422016, &r.MetricName)
//line app/vmselect/loki/query_range_response.qtpl:28
	qw422016.N().S(`,"values":`)
//line app/vmselect/loki/query_range_response.qtpl:29
	streamvaluesWithTimestamps(qw422016, r.Values, r.Timestamps)
//line app/vmselect/loki/query_range_response.qtpl:29
	qw422016.N().S(`}`)
//line app/vmselect/loki/query_range_response.qtpl:31
}

//line app/vmselect/loki/query_range_response.qtpl:31
func writequeryRangeLine(qq422016 qtio422016.Writer, r *netstorage.Result) {
//line app/vmselect/loki/query_range_response.qtpl:31
	qw422016 := qt422016.AcquireWriter(qq422016)
//line app/vmselect/loki/query_range_response.qtpl:31
	streamqueryRangeLine(qw422016, r)
//line app/vmselect/loki/query_range_response.qtpl:31
	qt422016.ReleaseWriter(qw422016)
//line app/vmselect/loki/query_range_response.qtpl:31
}

//line app/vmselect/loki/query_range_response.qtpl:31
func queryRangeLine(r *netstorage.Result) string {
//line app/vmselect/loki/query_range_response.qtpl:31
	qb422016 := qt422016.AcquireByteBuffer()
//line app/vmselect/loki/query_range_response.qtpl:31
	writequeryRangeLine(qb422016, r)
//line app/vmselect/loki/query_range_response.qtpl:31
	qs422016 := string(qb422016.B)
//line app/vmselect/loki/query_range_response.qtpl:31
	qt422016.ReleaseByteBuffer(qb422016)
//line app/vmselect/loki/query_range_response.qtpl:31
	return qs422016
//line app/vmselect/loki/query_range_response.qtpl:31
}

//line app/vmselect/loki/query_range_response.qtpl:33
func StreamQueryRangeDatasResponse(qw422016 *qt422016.Writer, rs []netstorage.Result) {
//line app/vmselect/loki/query_range_response.qtpl:33
	qw422016.N().S(`{"status":"success","data":{"resultType":"streams","result":[`)
//line app/vmselect/loki/query_range_response.qtpl:39
	if len(rs) > 0 {
//line app/vmselect/loki/query_range_response.qtpl:40
		streamdatasQueryRangeLine(qw422016, &rs[0])
//line app/vmselect/loki/query_range_response.qtpl:41
		rs = rs[1:]

//line app/vmselect/loki/query_range_response.qtpl:42
		for i := range rs {
//line app/vmselect/loki/query_range_response.qtpl:42
			qw422016.N().S(`,`)
//line app/vmselect/loki/query_range_response.qtpl:43
			streamdatasQueryRangeLine(qw422016, &rs[i])
//line app/vmselect/loki/query_range_response.qtpl:44
		}
//line app/vmselect/loki/query_range_response.qtpl:45
	}
//line app/vmselect/loki/query_range_response.qtpl:45
	qw422016.N().S(`]}}`)
//line app/vmselect/loki/query_range_response.qtpl:49
}

//line app/vmselect/loki/query_range_response.qtpl:49
func WriteQueryRangeDatasResponse(qq422016 qtio422016.Writer, rs []netstorage.Result) {
//line app/vmselect/loki/query_range_response.qtpl:49
	qw422016 := qt422016.AcquireWriter(qq422016)
//line app/vmselect/loki/query_range_response.qtpl:49
	StreamQueryRangeDatasResponse(qw422016, rs)
//line app/vmselect/loki/query_range_response.qtpl:49
	qt422016.ReleaseWriter(qw422016)
//line app/vmselect/loki/query_range_response.qtpl:49
}

//line app/vmselect/loki/query_range_response.qtpl:49
func QueryRangeDatasResponse(rs []netstorage.Result) string {
//line app/vmselect/loki/query_range_response.qtpl:49
	qb422016 := qt422016.AcquireByteBuffer()
//line app/vmselect/loki/query_range_response.qtpl:49
	WriteQueryRangeDatasResponse(qb422016, rs)
//line app/vmselect/loki/query_range_response.qtpl:49
	qs422016 := string(qb422016.B)
//line app/vmselect/loki/query_range_response.qtpl:49
	qt422016.ReleaseByteBuffer(qb422016)
//line app/vmselect/loki/query_range_response.qtpl:49
	return qs422016
//line app/vmselect/loki/query_range_response.qtpl:49
}

//line app/vmselect/loki/query_range_response.qtpl:51
func streamdatasQueryRangeLine(qw422016 *qt422016.Writer, r *netstorage.Result) {
//line app/vmselect/loki/query_range_response.qtpl:51
	qw422016.N().S(`{"metric":`)
//line app/vmselect/loki/query_range_response.qtpl:53
	streammetricNameObject(qw422016, &r.MetricName)
//line app/vmselect/loki/query_range_response.qtpl:53
	qw422016.N().S(`,"values":`)
//line app/vmselect/loki/query_range_response.qtpl:54
	streamdatasWithTimestamps(qw422016, r.Datas, r.Timestamps)
//line app/vmselect/loki/query_range_response.qtpl:54
	qw422016.N().S(`}`)
//line app/vmselect/loki/query_range_response.qtpl:56
}

//line app/vmselect/loki/query_range_response.qtpl:56
func writedatasQueryRangeLine(qq422016 qtio422016.Writer, r *netstorage.Result) {
//line app/vmselect/loki/query_range_response.qtpl:56
	qw422016 := qt422016.AcquireWriter(qq422016)
//line app/vmselect/loki/query_range_response.qtpl:56
	streamdatasQueryRangeLine(qw422016, r)
//line app/vmselect/loki/query_range_response.qtpl:56
	qt422016.ReleaseWriter(qw422016)
//line app/vmselect/loki/query_range_response.qtpl:56
}

//line app/vmselect/loki/query_range_response.qtpl:56
func datasQueryRangeLine(r *netstorage.Result) string {
//line app/vmselect/loki/query_range_response.qtpl:56
	qb422016 := qt422016.AcquireByteBuffer()
//line app/vmselect/loki/query_range_response.qtpl:56
	writedatasQueryRangeLine(qb422016, r)
//line app/vmselect/loki/query_range_response.qtpl:56
	qs422016 := string(qb422016.B)
//line app/vmselect/loki/query_range_response.qtpl:56
	qt422016.ReleaseByteBuffer(qb422016)
//line app/vmselect/loki/query_range_response.qtpl:56
	return qs422016
//line app/vmselect/loki/query_range_response.qtpl:56
}
